tap "argon/mas"
tap "delphinus/sfmono-square"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "nektos/tap"
tap "sanemat/font"
cask "xquartz"
brew "openssl"
brew "readline"
brew "flac"
brew "ffmpeg"
brew "cmake"
brew "ctags"
brew "curl"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "go"
brew "graphviz"
brew "gtk+"
brew "gtk+3"
brew "htop"
brew "hub"
brew "imagemagick"
brew "imagemagick@6"
brew "imlib2"
brew "jq"
brew "less"
brew "lesspipe"
brew "lftp"
brew "libcaca"
brew "libicns"
brew "libiconv"
brew "librsvg"
brew "libusb"
brew "libxml2"
brew "mas"
brew "mplayer"
brew "mysql@5.6"
brew "nkf"
brew "node"
brew "openjdk"
brew "peco"
brew "qt"
brew "postgresql"
brew "pyenv"
brew "rename"
brew "sox"
brew "testssl"
brew "tig"
brew "tmux"
brew "trash"
brew "tree"
brew "v8@3.15"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "delphinus/sfmono-square/sfmono-square"
brew "heroku/brew/heroku"
brew "nektos/tap/act"
cask "alfred"
cask "authy"
cask "chromedriver"
cask "clipy"
cask "dbeaver-community"
cask "disk-inventory-x"
cask "docker"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "fork"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "handbrake"
cask "handbrakebatch"
cask "imageoptim"
cask "iterm2"
cask "libreoffice"
cask "mi"
cask "microsoft-edge"
cask "musescore"
cask "ngrok"
cask "optimage"
cask "owasp-zap"
cask "skype"
cask "slack"
cask "sonic-pi"
cask "soundsource"
cask "sourcetree"
cask "sublime-text"
cask "switchhosts"
cask "thunderbird"
cask "typora"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "blackhole"
mas "1Password 7", id: 1333542190
mas "Bandwidth+", id: 490461369
mas "BetterSnapTool", id: 417375580
mas "Day One", id: 1055511498
mas "Final Cut Pro", id: 424389933
mas "Geekbench 4", id: 1175706108
mas "LINE", id: 539883307
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 1289197285
mas "News Explorer", id: 1032670789
mas "Parallels Client", id: 600925318
mas "Sequel Ace", id: 1518036000
mas "SiteSucker", id: 442168834
mas "Switch Plus", id: 434744386
mas "The Unarchiver", id: 425424353
mas "Twitter", id: 1482454543
mas "WinArchiver", id: 413215883
mas "Xcode", id: 497799835
