tap "argon/mas"
tap "delphinus/sfmono-square"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "nektos/tap"
tap "sanemat/font"
tap "teamookla/speedtest"
tap "yt-dlp/taps"
brew "glib"
brew "python@3.9"
brew "atk"
brew "awscli"
brew "asdf"
brew "zstd"
brew "bzt"
brew "cmake"
brew "ctags"
brew "curl"
brew "coreutils"
brew "exa"
brew "flac"
brew "gnutls"
brew "harfbuzz"
brew "gobject-introspection"
brew "ffmpeg"
brew "pango"
brew "ffmpeg"
brew "fontforge"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "go"
brew "librsvg"
brew "graphviz"
brew "gsettings-desktop-schemas"
brew "gtk+"
brew "gtk+3"
brew "htop"
brew "hub"
brew "imagemagick"
brew "imagemagick@6"
brew "imlib2"
brew "jc"
brew "jq"
brew "jump"
brew "krb5"
brew "lazygit"
brew "less"
brew "lesspipe"
brew "lftp"
brew "libcaca"
brew "libicns"
brew "libiconv"
brew "libusb"
brew "libxml2"
brew "qemu"
brew "lima"
brew "mas"
brew "zlib"
brew "mariadb"
brew "nkf"
brew "node"
brew "openjdk"
brew "peco"
brew "postgresql@14"
brew "pyenv"
brew "qt"
brew "rename"
brew "ruby"
brew "sox"
brew "starship"
brew "testssl"
brew "tig"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "yq"
brew "zsh"
brew "delphinus/sfmono-square/sfmono-square"
brew "heroku/brew/heroku"
brew "teamookla/speedtest/speedtest"
brew "yt-dlp/taps/yt-dlp"
cask "1password-cli"
cask "alfred"
cask "authy"
cask "aws-vault"
cask "bdash"
cask "blackhole-16ch"
cask "choosy"
cask "chromedriver"
cask "clipy"
cask "dbeaver-community"
cask "devtoys"
cask "disk-inventory-x"
cask "docker"
cask "drawio"
cask "evernote"
cask "firefox"
cask "font-sauce-code-pro-nerd-font"
cask "font-ubuntu-mono-nerd-font"
cask "fork"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "handbrake"
cask "handbrakebatch"
cask "imageoptim"
cask "iterm2"
cask "jetbrains-toolbox"
cask "mi"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mountain-duck"
cask "musescore"
cask "ngrok"
cask "obs"
cask "optimage"
cask "owasp-zap"
cask "sublime-text"
cask "switchhosts"
cask "thunderbird"
cask "utm"
cask "vagrant"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
mas "Bandwidth+", id: 490461369
mas "BetterSnapTool", id: 417375580
mas "Geekbench 4", id: 1175706108
mas "GoodNotes", id: 1444383602
mas "iReal Pro", id: 409035833
mas "Kindle", id: 405399194
mas "Mactracker", id: 430255202
mas "Sequel Ace", id: 1518036000
mas "SiteSucker", id: 442168834
mas "Slack", id: 803453959
mas "Switch Plus", id: 434744386
mas "Tailscale", id: 1475387142
mas "The Unarchiver", id: 425424353
mas "WinArchiver", id: 413215883
mas "Xcode", id: 497799835
