name: Test for macOS install

on: [push]

jobs:
  test:
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: |
          make deploy
          make init
          make update
          make test