name: Test for macOS install

on: [push]

jobs:
  test:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Init
        run: |
          make deploy
          make init
      - name: Update
        run: |
          make update
      - name: Test
        run: |
          make test
